// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n = Integer.parseInt(args[0]);
		int stepCounter = 0;
		int randomBigger = 0;

		while (stepCounter < n) {
			stepCounter++ ;
			double random = Math.random() ;
			if (random > 0.5) {
				randomBigger++;
			}
		}

		int randomSmaller = n-randomBigger;

		System.out.println("> 0.5 " + randomBigger +"times");
		System.out.println("<= 0.5 " + randomSmaller + " times");

		double randomSmallerDouble = randomSmaller;
		double randomBiggerDouble= randomBigger;
		double ratio = randomBiggerDouble/ randomSmallerDouble ;
		if (randomSmaller > 0 && randomBigger > 0) {
		System.out.println("Ratio: " + ratio);
		}
	}
}
